# GitHub Action for Laravel with MySQL and Redis
name: API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-versions: ['8.1', '8.2']
        laravel: [10.*]

    name: Laravel ${{ matrix.laravel }} - PHP v${{ matrix.php }}
    
    services:
      mysql:
        image: mysql:8.0.33
        env:
          MYSQL_ROOT_PASSWORD: pass
          MYSQL_DATABASE: 'laravel_cicd_testing'
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -ppass"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify laravel_cicd_testing DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -ppass -e "SHOW DATABASES LIKE 'laravel_cicd_testing'"

      - name: Create 2nd Database
        run: mysql --host 127.0.0.1 --port 3306 -uroot -ppass -e "CREATE DATABASE IF NOT EXISTS laravel_cicd_testing_second;"

      - name: Verify laravel_cicd_testing DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -ppass -e "SHOW DATABASES LIKE 'laravel_cicd_testing_second'"
